version: '3.8'
services:
  db-credit:
    image: postgres:15
    container_name: postgres-credit
    environment:
      - POSTGRES_DB=credit_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"