# --- Server Configuration ---
spring.application.name=credit-service
server.port=8082

# --- Database ---
spring.datasource.url=jdbc:postgresql://localhost:5432/credit_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Kafka Bootstrap Servers
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.linger.ms=10
spring.kafka.producer.properties.batch.size=16384
spring.kafka.producer.properties.compression.type=snappy
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Consumer
spring.kafka.consumer.group-id=listing-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.max.poll.records=100
spring.kafka.consumer.properties.session.timeout.ms=30000

# Admin
spring.kafka.admin.properties.bootstrap.servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.database=0

# Connection pool (requires commons-pool2)
spring.data.redis.lettuce.pool.max-active=10
spring.data.redis.lettuce.pool.max-idle=5
spring.data.redis.lettuce.pool.min-idle=1
spring.data.redis.lettuce.pool.max-wait=2000ms

server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8

# --- Swagger ---
springdoc.swagger-ui.path=/swagger-ui.html

# --- Fix PayOS JSON Mapping Error ---
# ÃÂÃÂp Jackson bÃÂ¡ÃÂ»ÃÂ qua cÃÂÃÂ¡c trÃÂÃÂ°ÃÂ¡ÃÂ»ÃÂng lÃÂ¡ÃÂºÃÂ¡ (nhÃÂÃÂ° expiredAt) trÃÂÃÂªn toÃÂÃÂ n hÃÂ¡ÃÂ»ÃÂ thÃÂ¡ÃÂ»ÃÂng
spring.jackson.deserialization.fail-on-unknown-properties=false

# --- PayOS Keys (Tham chiÃÂ¡ÃÂºÃÂ¿u tÃÂ¡ÃÂ»ÃÂ« Environment Variables bÃÂ¡ÃÂºÃÂ¡n ÃÂÃÂÃÂÃÂ£ ÃÂÃÂÃÂ¡ÃÂºÃÂ·t) ---
PAYOS_CLIENT_ID=478a2b04-5307-4c3f-8868-dc5bf540f6ba
PAYOS_API_KEY=e21aa6d2-6491-438f-b6b6-c57878f578e5
PAYOS_CHECKSUM_KEY=290a08d456205935552acb1eac67473fd855f29a9be40810eb93b21d1bbda456