# --- Server Configuration ---
spring.application.name=credit-service
server.port=8082

# --- Database ---
spring.datasource.url=jdbc:postgresql://localhost:5433/credit_db?options=-c%20timezone=UTC
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# --- Fix Kafka Error ---
spring.kafka.bootstrap-servers=localhost:9092

server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8

# --- Swagger ---
springdoc.swagger-ui.path=/swagger-ui.html

# --- Fix PayOS JSON Mapping Error ---
# Ép Jackson bỏ qua các trường lạ (như expiredAt) trên toàn hệ thống
spring.jackson.deserialization.fail-on-unknown-properties=false

# --- PayOS Keys (Tham chiếu từ Environment Variables bạn đã đặt) ---
PAYOS_CLIENT_ID=${PAYOS_CLIENT_ID}
PAYOS_API_KEY=${PAYOS_API_KEY}
PAYOS_CHECKSUM_KEY=${PAYOS_CHECKSUM_KEY}